export const FETCH_DASHBOARD_DATA_REQUEST = 'FETCH_DASHBOARD_DATA_REQUEST'
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS'
export const FETCH_DASHBOARD_DATA_FAILURE = 'FETCH_DASHBOARD_DATA_FAILURE'

export const SELECT_INDEX = 'SELECT_INDEX';
export const SELECT_INDEX_SUCCESS = 'SELECT_INDEX_SUCCESS';